codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 0.80
        threshold: 1%
        paths:
          - cmd/
          - internal/
          - pkg/
          - api/
    patch:
      default:
        target: 0.80
        threshold: 0.5%
        paths:
          - cmd/
          - internal/
          - pkg/
          - api/

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "api/**/zz_generated.*.go"
  - "**/*.deepcopy.go"
  - "**/*.pb.go"
  - "**/zz_generated.*.go"
  - "**/mocks/**"
  - "**/testdata/**"
  - "test/golden/**"
  - "config/**"
  - "docs/**"
  - "examples/**"
  - "bin/**"
  - "hack/**"
  - "*.md"
  - "Makefile*"
