apiVersion: mcpruntime.org/v1alpha1
kind: MCPServer
metadata:
  name: example-mcp-server
  namespace: default
spec:
  # Image pushed via `mcp-runtime registry push --image example-app:latest --name example-app`
  image: 10.96.23.191:5000/example-app
  imageTag: latest
  replicas: 1
  port: 8088
  servicePort: 80
  ingressPath: /example-app
  ingressHost: example.local
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  envVars:
    - name: ENV_VAR_1
      value: "value1"
    - name: ENV_VAR_2
      value: "value2"
